@startuml

title <size:20>Flujo de datos Consumo Combustible\n<size:12>Proceso de integracion de datos desde API a base de datos\n<size:10>Python|SQL|ORACLE
' Footer con comentario sobre las mejoras
footer Automatización del registro de consumo de combustible con Python. Se eliminó la entrada manual, lo que garantizó\n la precisión y permitió la toma de decisiones en tiempo real para optimizar los gastos de la flota

|#CAFFC4|API solinftec.com|
start
:Consumir datos de la API;

|#F0CA92|DB Oracle 19c|
:Insertar datos en la tabla ABASTECIMIENTO;
if (Inserción exitosa?) then (sí)
  :Insertar registro en la tabla LOG;
else (no)
  :Manejar error de inserción;
endif
end
@enduml